---
# Название пакета, для которого хотим получить информацию. Указывается регулярное выражение для поиска
giaip_package_name_regex: "^postgres"

# Файл .csv, в котором собрана найденная информация. Сохраняется на хосте, откуда запускается Ansible
giaip_file_info_path: ./file_info.csv
