---
dfr_install_packages:
  - expect
  - freeradius
  - freeradius-utils
  - freeradius-krb5
  - samba
  - samba-winbind
  - samba-client
  - krb5-workstation
  - oddjob
  - oddjob-mkhomedir
  - samba-winbind-clients
  - samba-common-tools

dfr_admin_AD_username: "{{ cli_admin_AD_username }}"
dfr_admin_AD_pass: "{{ cli_admin_AD_pass }}"

dfr_short_network: "{{ ansible_host.split('.')[:3] | join('.') }}"
