---
dfr_domain_name: >-
  {{ (inventory_hostname.split('.', 1)[1]
    if inventory_hostname.find('.') != -1
    else "altdomain.test") }}

dfr_domain_controllers:
  - dc1.altdomain.test
  - dc2.altdomain.test
  - dc3.altdomain.test

dfr_placement: >-
  {{ (group_names | select('match','^.*_placement$') | list | first).split('_')[0]
    | default('default_secret') }}

dfr_radius_clients:
  WiFi:
    ipaddr: "{{ dfr_short_network }}.0/24"
    secret: "{{ dfr_vault_secret_radius_clients[dfr_placement] }}"
    comment: "Wi-fi office"
