$ANSIBLE_VAULT;1.2;AES256;deploy_dhcp
64323663656133653433653463353033386137623239346236303339303530306530356533333664
3866383134356561333739666534376639636561303765360a613234366664346636613864373236
33633966323961613535646231303866373137373730663765306563393163316661633061613964
6236393436363536390a393365356464613062316639323261393565643137663633343136346239
35663261356364366465316130376534623136303937393535343264663063363661313233616666
38316666373633383762383530326638613037356136613133333965613533313933316636333761
32303337616438643761366231356231623061323666623365383763333232303637353533663037
63633662333837656639366335623632306564313233623763386234386361666537326234623139
30323866643361396233386264313137313332643363643165333565653663333330343334343866
33343038336136386233323966316631646565333235356539373238393930363832356339616537
33616232313237656462366139323637376331366534366139306566323232653235333765393532
64333534373430643562366534356639623434333162376465333964386564303662323562396435
6562
